### ISSUE TITLE
How do I add facebook pages?

### ISSUE THREAD

**Issue by darren3** [irfancharania/fb-feed-gen#1]
Hello, I have been looking for a facebook rss feed generator since they depreciated public page rss. I have deployed your app to heroku, how do I add my facebook pages and where will the urls for the rss feeds be? Thanks.

**Comment by irfancharania** [comment]
Did you open the app after you deployed it?
Go to the Heroku dashboard, click on the deployed app, on the top right click the 3 vertical dots and select "open app".
Should be straight forward from there...

**Comment by darren3** [comment]
Hello Irfan, thanks for the response. No I hadn't, had never used Heroku before. Me being dumb. Would you be able to check a couple of faebook pages for me? Most of my pages seem to work but I have had a couple of errors. facebook.com/900mobile gives me "No posts found. Are you sure you put in the correct username?" and facebook.com/checkoutsmart gives me "ValueError
ValueError: Unknown string format". Thanks, really appreciate you making this app.

**Comment by irfancharania** [comment]
Not sure why those two are throwing errors. 
I'll have a look later.

**Comment by darren3** [comment]
Great thanks.

**Comment by irfancharania** [comment]
I just updated it. 

1. Checkoutsmart should now work. It wasn't parsing human readable dates.
2. 900mobile won't work. The way I'm doing this is by scraping the mobile basic site, and on the 900mobile site they don't have any links for the individual posts. Those links are there on the regular mobile site, the full site, and on their official graph api. It would mean a lot of work to switch over to using those, and I'm not going to do that.

If you don't want to bother with figuring out how to update your deployed heroku app using git, you can probably delete it, and redeploy with the same name.

**Comment by darren3** [comment]
Ok great thanks Irfan.
