### ISSUE TITLE
Feed errors

### ISSUE THREAD

**Issue by darren3** [irfancharania/fb-feed-gen#2]
Hello Irfan, I have come across a few more errors. Would you be able to look at them?

The following pages give me the error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 119: ordinal not in range(128)"

https://www.facebook.com/FrankieBoyleFans
https://www.facebook.com/stephenmerchantofficial
https://www.facebook.com/TheHobbitUK

The following pages give me the error "ValueError: title is required"

https://www.facebook.com/Blinddaley
https://www.facebook.com/BastianSchweinsteiger
https://www.facebook.com/SchneiderlinMo4
https://www.facebook.com/theprodigyofficial
https://www.facebook.com/NfcRing

And the following pages give me "Invalid username provided"

https://www.facebook.com/Marlborough-Neighbourhood-Policing-Team
https://www.facebook.com/The-Crown-Anchor-Ramsbury
https://www.facebook.com/The-Lamb-Inn
https://www.facebook.com/Old-Forge-Tropicals

I have set up a lot of pages now and your app is working really well, really happy to have found it.

Thanks.

**Comment by irfancharania** [comment]
Dude you've got more feeds than I do! 😀

Probably why you're finding issues I never came across. The second and
third set of links I think I know the fix just from your description. The
first set I'll have to play around with to see.

I'll have a look tonight or tomorrow.

**Comment by darren3** [comment]
Great thanks for your help Irfan.

**Comment by irfancharania** [comment]
All fixed.

The last set is actually in a different format like this
https://www.facebook.com/pages/Old-Forge-Tropicals/163077410408333

**Comment by darren3** [comment]
Great, thanks Irfan. Will have a look when I finish work.

**Comment by darren3** [comment]
Thanks again Irfan. Can confirm all my feeds are now working. Cheers.

**Comment by darren3** [comment]
Do you think there would be a way of getting a feed from a community page?

https://www.facebook.com/MarlboroughNewsOnline

**Comment by irfancharania** [comment]
Clicking that link doesn't work for me... Just goes to a page not found

**Comment by darren3** [comment]
Your right I just tried from an incognito browser tab not signed in and get the same. Can't be a public page then,  community pages didn't have RSS feeds when facebook provided public rss feeds. Not to worry, thanks for looking.
