### ISSUE TITLE
Feeds from Private Pages Not Working

### ISSUE THREAD

**Issue by thepianoman3** [irfancharania/fb-feed-gen#7]
Hi, first of all, thanks for your awesome work on this! I'm super excited to find it. I noticed that private pages (this for example: https://www.facebook.com/fieldwork.NRC/) don't seem to work. It says that it can't find any posts. Any ideas for a workaround on this? Thanks!

**Comment by irfancharania** [comment]
This is strictly for public pages. 

For private pages, you'd have to use FB's graph API and provide it your API key. There are other projects out there that use the official way of doing things rather than the inefficient way I'm scraping the pages.

**Comment by thepianoman3** [comment]
I'm curious- what would the efficient way involve? Thanks


________________________________

**Comment by irfancharania** [comment]
Generate a feed using their API: https://developers.facebook.com/docs/graph-api/
